name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Output
          path: build/libs/*.jar
